### ISSUE TITLE
add jest

### ISSUE THREAD

**Issue by andr-ii** [andr-ii/nuti#27]

**Comment by BagasAnjasmara** [comment]
https://github.com/andr-ii/nuti/blob/6fb069bfe59e609ecedaccb71a923e0928a0f027/.github/workflows/coverage.yml

**Comment by BagasAnjasmara** [comment]
coverage.yml

**Comment by BagasAnjasmara** [comment]
`[https://github.com/andr-ii/nuti/blob/6fb069bfe59e609ecedaccb71a923e0928a0f027/.github/workflows/coverage.yml](https://github.com/andr-ii/nuti/blob/6fb069bfe59e609ecedaccb71a923e0928a0f027/.github/workflows/coverage.yml) `

**Comment by andr-ii** [comment]
Hi @BagasAnjasmara !
What do you mean by sending these links?
